mouse_support = true
paste_support = true
frame_rate = 60.0
show_status_bar = true
show_title_bar = true
theme_enable = true
theme_filename = "themes/onedark.toml"
take_api_id_from_telegram_config = true
take_api_hash_from_telegram_config = true
